### ISSUE TITLE
Crash after cancel

### ISSUE THREAD

**Issue by httsmvkcom** [HirbodBehnam/Downloader-Bot#1]
Bot write "Canceled" and crash with error
`Unhandled Exception: System.IO.IOException: The process cannot access the file 'test100Mb.db' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.DirectoryInfo.Delete(Boolean recursive)
   at Downloader_Bot.Program.Bot_OnMessage(Object sender, MessageEventArgs e) in C:\Users\Иван\Download-bot\Downloader Bot\Program.cs:line 197
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by HirbodBehnam** [comment]
If you still face this issue please tell me to reopen this issue.
